services:
  app:
    image: chme0039-pytorch-basic:1.4
    container_name: pytorch-basic-container
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    ports:
      - "8888:8888"
      - "8501:8501"
    volumes:
      - .:/app:Z
      - ./data:/app/data:Z
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
